layout_spectrum: 0.2666700807408347
typography_spectrum: 0.43377637441823313
color:
  brandStrength: 0.5066830767203344
  lightness: 0.354510025887999
  saturation: 0.2389638364123236
  rhythmicContrast: 0.572983746549926
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sund Fiskerimuseum
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a3afe87c-9bda-491b-b3e5-9b8aaef60301.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a3afe87c-9bda-491b-b3e5-9b8aaef60301.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3f508bd3-f3b1-4371-9ece-311c68daafd7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3f508bd3-f3b1-4371-9ece-311c68daafd7.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: 'Smeden I Sund '
description: 'The Authentic Rough Diamond Of Lofoten  '
purpose:
  - type: phone
    url: 'tel:004791371718'
    label: Phone Booking/Sale
  - type: contact
    url: 'mailto:sund.fiskerimuseum@gmail.com'
    label: Mail
github: true
author:
  name: Smeden i Sund
  email: sund.fiskerimuseum@gmail.com
  url: 'https://www.facebook.com/SmedeniSund/'
