layout_spectrum: 0.2666700807408347
typography_spectrum: 0.43377637441823313
color:
  brandStrength: 0.5066830767203344
  lightness: 0.354510025887999
  saturation: 0.2389638364123236
  rhythmicContrast: 0.572983746549926
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Sund Fiskerimuseum
content: []
title: 'Smeden I Sund '
description: 'The Authentic Rough Diamond Of Lofoten  '
purpose:
  - type: phone
    url: 'tel:004791371718'
    label: Phone Booking/Sale
  - type: contact
    url: 'mailto:sund.fiskerimuseum@gmail.com'
    label: Mail
github: true
author:
  name: Smeden i Sund
  email: sund.fiskerimuseum@gmail.com
  url: 'https://www.facebook.com/SmedeniSund/'
